### ISSUE TITLE
java.lang.reflect.InvocationTargetException caused by: java.lang.StackOverflowError

### ISSUE THREAD

**Issue by dynamiskduo** [nicfel/Recombination#4]
Hello :)

Thank you for a nice package - very useful!
I am attempting to follow your tutorial on some whole-genome CoV data, and it runs well for some time, but then it crashes with the following message:

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at beast.app.beastapp.BeastLauncher.run(Unknown Source)
	at beast.app.beastapp.BeastLauncher.main(Unknown Source)
Caused by: java.lang.StackOverflowError
	at recombination.network.BreakPoints.and(Unknown Source)
	at recombination.likelihood.NetworkLikelihood.traversalRoots(Unknown Source)

Do you know what happens and if there is anything I can do to prevent it? 

Best,
Amanda

**Comment by nicfel** [comment]
Dear Amanda,
The issue here is that throughout the MCMC, the number of nodes in the network can change, in theory up to infinity. The reason is that the network can be longer than any local tree. If you setup the network prior, there is an option for maxHeightRatio. If you set that value to, e.g., 1.5, this error shouldn't occur anymore.
